# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16c0ceb73899eb29889522286258ad6f150d12a8337033faa219c0dad792a5a6400db6276346157e80c156687d7f781a429c4ac1e6df1ef037566c021fb47212

test:
  secret_key_base: fbeacbeda08e2b2621a9b9d3786ac8b703ec20ed950421005d2b1a2581ddd299a9e5031e666e4994fbd75051d1f8ae4db014b2ccac5fc8dcd4d511b17563c229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
